### PR TITLE
Fix error in comments for xthread.comp

### PR DESCRIPTION
**Pull request by ArcEye**
Comments said it would create xthread for each component, which of course it will not
just gets called in rtapi_main()

### CODE REVIEW

**Comment by mhaberler** [comment]
your call. I have no strong opinion one way or the other.
In terms of support, I'd rather support one than two, but not much trouble likely

**Comment by ArcEye** [comment]
If you are happy with a default undocumented inclusion of the xthread creation in all comps
that is fine, saves the user having to do anything when writing the comp and they don't have to use it or even know it exists if it is of no relevance to them.

Will be 2 minutes work to remove the option and the conditional inclusion based upon it.

If someone does want to use them, the only method is to generate a C template then modify that.
Presume that is OK too?

**Comment by mhaberler** [comment]
I dont quite understand - what I suggest is a default use of xthread_functs

if you want the legacy API you could do a legacy_funct knob, but I dont see the point really, no difference to be expected, its just a less flexible form of parameter passing

could it be we're talking past each other?

**Comment by ArcEye** [comment]
At tangents possibly:)
I will remove the option selection and make the use default tomorrow

**Comment by ArcEye** [comment]
Closing this one, now amended to be default

**Pull request closed without merging**
