### PR TITLE
Convert halmeter and halscope to use iterators to access objects

### PR DESCRIPTION
**Pull request by ArcEye**
Signed-off-by: Mick <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by ArcEye** [comment]
This one contains just files that will have been untouched by you
(you just #ifeq (1,0) in the Makefile to stop any of it being built, that needs reversing)

When you have looked at this I will do a seperate PR for halcmd_commands.c, once I have diff'ed your new version against my old one and made changes

**Comment by ArcEye** [comment]
Added Submakefile required to build again

**Comment by ArcEye** [comment]
Now done a fresh pull from your branch, 
Whilst halscope builds OK with `make -i` to get rid of cython errors, halscope now crashes and locks up MK when you try to load a pin into a channel.
On my out of date previous pull it worked.

**Comment by ArcEye** [comment]
halscope now throwing errors and locking up in my previous repo too, having worked for past 2 days

Pulling whole thing until have time to figure out what is causing it

**Comment by mhaberler** [comment]
> Am 22.07.2015 um 12:38 schrieb ArcEye <notifications@github.com>:
> 
> This one contains just files that will have been untouched by you
> (you just #ifeq (1,0) in the Makefile to stop any of it being built, that needs reversing)
> 
> When you have looked at this I will do a seperate PR for halcmd_commands.c, once I have diff'ed your new version against my old one and made changes

ok, it looks github-mah/halobject-header is approaching 'stability' - the worst is over, runtesting now on various platforms


want to pick your gtk stuff ontop and post a PR?

**Pull request closed without merging**
