### PR TITLE
instcomp formatting for pin_ptr changed to prevent pin name mangling

### PR DESCRIPTION
**Pull request by ArcEye**
New HC_SMP_SAFE stamp for v2 components

New convenience get/set macros for use in user FUNCTION(_)

New debouncev2.icomp showing above

Signed-off-by: Mick <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by ArcEye** [comment]
The macros are just a workaround for now, to make manual conversion easier.

The pins now have matching names to the v1 pins, screwed up the formatting initially, trying to convert the format from pins to pin_ptrs

**Comment by ArcEye** [comment]
A few more for you to play with

I am guessing that incr_u32_pin() increments a pin value by the value specified?

Not had cause to use it, but added to the macros to go with my equivilent of incr_s32_pin()
which catered for a specific bit of code in debouncev2

**Comment by ArcEye** [comment]
85 done, just 4 (including 2 of the most arcane and awfully written) left

**Comment by mhaberler** [comment]
already merged into ck-integration

**Pull request closed without merging**
