### PR TITLE
Amended instcomp, name exported xthread functions as <instance>.funct

### PR DESCRIPTION
**Pull request by ArcEye**
New directory in tests/ for 16 i_comp specific tests

Updated instcomp.asciidoc re change to xthread funct name

Signed-off-by: Mick <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by mhaberler** [comment]
Hi Mick,

added some build support: https://github.com/mhaberler/machinekit/commit/12201a929a0615783f29bc7fea41eacded6832ff

does not quite work yet, it has to do with generating manpages

example:


hal/i_components/Submakefile:32: Building ../man/man9/i_bitslice.9icomp (from hal/i_components/i_bitslice.icomp) (hal/i_components/i_bitslice.icomp ../bin/instcomp newer)
../bin/instcomp --document -o ../man/man9/i_bitslice.9icomp hal/i_components/i_bitslice.icomp
Traceback (most recent call last):
  File "../bin/instcomp", line 1572, in <module>
    main()
  File "../bin/instcomp", line 1527, in main
    document(f, outfile)
  File "../bin/instcomp", line 1298, in document
    print >>f, " (%s=%0*d..%0*d)" % ("M" * sz, sz, 0, sz, array-1),
TypeError: unsupported operand type(s) for -: 'str' and 'int'
make: *** [../man/man9/i_bitslice.9icomp] Error 1



to see the gory details, run build as
make V=1 VV=1

probably minor

jeesh, also need to gitignore these pages

**Comment by ArcEye** [comment]
I will look at it later today.
I had a similar error when I hacked a copy of the existing Submakefile 
in /components

Suspect that it uses one of the rules that I modified to cater for 
instance params and now it can't resolve it properly

**Comment by mhaberler** [comment]
> Am 05.04.2015 um 08:29 schrieb ArcEye <notifications@github.com>:
> 
> I will look at it later today.
> I had a similar error when I hacked a copy of the existing Submakefile 
> in /components
> 
> Suspect that it uses one of the rules that I modified to cater for 
> instance params and now it can't resolve it properly

nope, its not the Submakefile, seems to type confusion on the array variable:

mah@nwheezy:~/machinekit-icomp/src$ ../bin/instcomp --document -o ../man/man9/i_bitslice.9icomp hal/i_components/i_bitslice.icompTraceback (most recent call last):
  File "../bin/instcomp", line 1572, in <module>
    main()
  File "../bin/instcomp", line 1527, in main
    document(f, outfile)
  File "../bin/instcomp", line 1298, in document
    print >>f, " (%s=%0*d..%0*d)" % ("M" * sz, sz, 0, sz, array-1),
TypeError: unsupported operand type(s) for -: 'str' and 'int'
mah@nwheezy:~/machinekit-icomp/src$ 

once that passes, I drape the *akefile magic around it ;)

**Comment by ArcEye** [comment]
>> nope, its not the Submakefile, seems to type confusion on the array variable:

That wasn't what I meant.  The 'it' I was talking about was instcomp

I only saw it when trying to hack the Submakefile, because that tries to build the man pages and I had not done so before

**Pull request merged**
