### PR TITLE
instcomp - check user funct code contains return and error message

### PR DESCRIPTION
**Pull request by ArcEye**
Modify i_components to remove spurious non-printing chars which
prevented proper string recognition

Machinekit branding in MODULEINFO entries

Signed-off-by: Mick <arceye@mgware.co.uk>

### CODE REVIEW

**Comment by ArcEye** [comment]
I'll leave you to put something suitable in the doc re return values

**Comment by mhaberler** [comment]
see http://static.mah.priv.at/public/HAL-instance-branch.html

**Comment by mhaberler** [comment]
and once the bot awakes..

**Comment by ArcEye** [comment]
On 08/04/15 14:01, Michael Haberler wrote:
>
> see http://static.mah.priv.at/public/HAL-instance-branch.html
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mhaberler/machinekit/pull/35#issuecomment-90907204>.
>

# NB: the /loadrt lutn/ command will happen automatically behind the # 
scenes if not yet loaded # and if you do not need it any more, destroy 
the instance

Didn't realise this bit, have been preloading and unloading the base 
component, will simplify things greatly.
Just tested with my sim config conversion and works fine

**Comment by mhaberler** [comment]
you can twist it in case there are any problems with it, its on by default and a halcmd variable:

halcmd: mah@nwheezy:~/machinekit-icomp/src$ halcmd -f -k
halcmd: autoload 
component autoload on 'newinst' is ON
halcmd: autoload 0
halcmd: autoload
component autoload on 'newinst' is OFF

**Pull request merged**
